#none of this works, really need to fix it at some point

sudo: required
language: node_js
node_js:
- '0.12'
before_install:
- curl https://install.meteor.com/ | sh
services: mongodb
script:
- meteor --test --release velocity:METEOR@1.3

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/99a89cd585bd27977159
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email: false
